# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'PR Check Fill'
description: 'A GitHub Action help you to check the filling format of PR.'
author: 'xrkffgg'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'pocket'
  color: 'gray-dark'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  filter-start:
    description: Content lines detection and filtering.
    required: true
  require-include:
    description: Further filtering lines.
  comment-body:
    description: Comment reminder when not filled in.
    required: true
  skip-title-start:
    description: Skip PR title start with.
  remove-symbol:
    description: Whether remove symbol

runs:
  using: 'node12'
  main: 'dist/index.js'
